project_id = "jegjrvglrjnhukxqkxoj"

[functions.trigger-deploy]
verify_jwt = false

[functions.upload-release]
verify_jwt = false

[functions.get-releases]
verify_jwt = false

[functions.update-release-url]
verify_jwt = false

[functions.forward-token-webhook]
verify_jwt = false
